# Generated by Django 4.2.7 on 2025-07-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_subscriptionplan_subscription"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorizationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("CONTAINS", "Contains"),
                            ("EQUALS", "Equals"),
                            ("STARTS_WITH", "Starts with"),
                            ("ENDS_WITH", "Ends with"),
                            ("REGEX", "Regular expression"),
                            ("GREATER_THAN", "Greater than"),
                            ("LESS_THAN", "Less than"),
                            ("GREATER_EQUAL", "Greater than or equal"),
                            ("LESS_EQUAL", "Less than or equal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("description", "Description"),
                            ("amount", "Amount"),
                            ("transaction_type", "Transaction Type"),
                            ("category", "Category"),
                        ],
                        max_length=50,
                    ),
                ),
                ("field_value", models.CharField(max_length=500)),
                ("priority", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="categories.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_rules",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "categorization_rules",
                "ordering": ["-priority", "name"],
                "unique_together": {("company", "name")},
            },
        ),
    ]
