# Generated by Django 4.2.7 on 2025-07-05 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razão Social"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "company_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEI", "Microempreendedor Individual"),
                            ("ME", "Microempresa"),
                            ("EPP", "Empresa de Pequeno Porte"),
                            ("LTDA", "Sociedade Limitada"),
                            ("SA", "Sociedade Anônima"),
                            (
                                "EIRELI",
                                "Empresa Individual de Responsabilidade Limitada",
                            ),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Empresa",
                    ),
                ),
                (
                    "business_sector",
                    models.CharField(blank=True, max_length=100, verbose_name="Setor"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Proprietário"),
                            ("admin", "Administrador"),
                            ("manager", "Gerente"),
                            ("accountant", "Contador"),
                            ("viewer", "Visualizador"),
                        ],
                        max_length=20,
                        verbose_name="Papel",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ingressou em"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário da Empresa",
                "verbose_name_plural": "Usuários das Empresas",
                "ordering": ["joined_at"],
                "unique_together": {("company", "user")},
            },
        ),
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                related_name="companies",
                through="companies.CompanyUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuários",
            ),
        ),
    ]
