# Generated by Django 4.2.7 on 2025-07-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("pluggy_connector_id", models.CharField(max_length=100, unique=True)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("supports_checking_account", models.BooleanField(default=True)),
                ("supports_savings_account", models.BooleanField(default=True)),
                ("supports_credit_card", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bank_providers",
                "ordering": ["name"],
            },
        ),
    ]
