# Generated by Django 4.2.7 on 2025-07-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_subscriptionplan_subscription"),
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pluggy_item_id", models.CharField(max_length=100)),
                ("pluggy_account_id", models.CharField(max_length=100, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Conta Corrente"),
                            ("SAVINGS", "Conta Poupança"),
                            ("CREDIT_CARD", "Cartão de Crédito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("agency", models.CharField(blank=True, default="", max_length=20)),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="banking.bankprovider",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "bank_accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
