# Generated by Django 4.2.7 on 2025-07-06 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0002_bankaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pluggy_transaction_id", models.CharField(max_length=100)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEBIT", "Débito"), ("CREDIT", "Crédito")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.CharField(max_length=500)),
                ("transaction_date", models.DateField()),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_pending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.bankaccount",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-transaction_date", "-created_at"],
                "unique_together": {("bank_account", "pluggy_transaction_id")},
            },
        ),
    ]
